apiVersion: extensions/v1beta1
kind: Deployment           
metadata:
  name: inventory                          
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory                      
    spec:
      containers:                       
      - name: inventory                     
        image: debajyotim/inventory             
        ports:
        - containerPort: 9200           
        env:
        - name: EUREKA_URL
          value: "http://eureka:admin@eureka-server:8761/eureka"
          #value: "http://173.193.75.122:30875/eureka"
